'use strict';
const $=id=>document.getElementById(id);
const wheel=location.pathname.includes('filterwheel'),fc3=location.pathname.includes('/focuser/1/'),eta=location.pathname.includes('/focuser/2/'),kind=wheel?'efw':eta?'eta':fc3?'fc3':'eaf',deviceType=wheel?'filterwheel':'focuser';
const setup='/setup/api/accessory/'+kind, api='/api/v1/'+deviceType+'/'+(eta?2:fc3?1:0)+'/';
const client=crypto.getRandomValues(new Uint32Array(1))[0]||1;
let profile,connected=false,busy=false,initialized=false;
async function json(url,body){const response=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok||result.error)throw Error(result.error||response.statusText);return result;}
async function alpaca(member,body){const params=new URLSearchParams({...body,ClientID:client});const response=await fetch(api+member+(body===undefined?'?'+params:''),body===undefined?{}:{method:'PUT',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params});const value=await response.json();if(value.ErrorNumber)throw Error(value.ErrorMessage);return value.Value;}
async function run(action){if(busy)return;busy=true;try{await action();$('status').textContent='Ready.';}catch(e){$('status').textContent=e.message;}finally{busy=false;}}
function options(items=[]){$('device').replaceChildren(new Option('No device selected',''));for(const item of items){const d=item.identity;$('device').add(new Option(d.model+' — '+d.serial,d.serial));}if(profile.serial&&!Array.from($('device').options).some(o=>o.value===profile.serial))$('device').add(new Option('Saved device — '+profile.serial,profile.serial));$('device').value=profile.serial||'';}
function renderFilters(){ $('filters').replaceChildren();profile.names.forEach((name,i)=>{const row=document.createElement('div');row.className='grid';const label=document.createElement('label');label.textContent='Slot '+(i+1);const input=document.createElement('input');input.value=name;input.maxLength=128;input.dataset.filterName=i;label.append(input);const offsetLabel=document.createElement('label');offsetLabel.textContent='Focus offset (steps)';const offset=document.createElement('input');offset.type='number';offset.step='1';offset.value=profile.focusOffsets[i];offset.dataset.filterOffset=i;offsetLabel.append(offset);row.append(label,offsetLabel);$('filters').append(row);});$('unidirectional').checked=profile.unidirectional;}
async function load(){const state=await json(setup);profile=state.profile;$('simulation').hidden=!state.simulation;options();renderFilters();$('connection').textContent=state.connected?'USB device is in use':'Disconnected';}
function motionControls(moving=false){$('move').disabled=!connected||moving;$('move-point').disabled=!connected||moving;$('cancel-queued').disabled=!connected;$('calibrate').disabled=!connected||moving;$('save-filters').disabled=moving;}
async function refresh(){if(!connected){motionControls();return;}const status=JSON.parse(await alpaca('action',{Action:'Regain.Status',Parameters:''}));if(status.error||status.fault){motionControls(true);throw Error(status.fault||'Device error '+status.error);}motionControls(status.moving);$('position').textContent=eta?'Back focus '+status.position+' µm · '+(status.moving?'Moving':'Idle')+' · '+status.points_um.map((p,i)=>'Point '+(i+1)+': '+p.toFixed(1)+' µm').join(' · '):wheel?(status.calibrating?'Calibrating… '+status.detected_slots+' slots detected. Waiting for the wheel to finish.':status.moving?'Moving…':'Slot '+(status.position+1)+' of '+status.slots):'Position '+status.position+' / '+status.max_step+' steps · '+(status.moving?'Moving':'Idle')+' · '+(status.temperature_c==null?'Temperature unavailable':status.temperature_c.toFixed(1)+' °C');if(!initialized){$('target').value=status.position+(wheel?1:0);$('target').max=wheel?status.slots:status.max_step;$('speed').value=status.speed??400;$('beep').checked=status.beep;$('reverse').checked=status.reverse;$('backlash').value=status.backlash;$('limit').value=status.max_step;initialized=true;}}
$('scan').onclick=()=>run(async()=>options(await json(setup+'/discover',{})));
$('device').onchange=()=>run(async()=>{profile={...profile,serial:$('device').value||null,names:[],focusOffsets:[]};await json(setup,profile);renderFilters();});
$('connect').onclick=()=>run(async()=>{await alpaca('connected',{Connected:!connected});connected=!connected;initialized=false;$('connect').textContent=connected?'Disconnect setup':'Connect for setup';$('device').disabled=connected;$('scan').disabled=connected;await load();$('connection').textContent=connected?'Connected for setup':'Disconnected';await refresh();});
$('move').onclick=()=>run(async()=>{const position=Number($('target').value)-(wheel?1:0);if(!Number.isInteger(position))throw Error('Enter a whole position');await alpaca(wheel?'position':'move',{Position:position});await refresh();});
$('calibrate').onclick=()=>run(async()=>{await alpaca('action',{Action:'Regain.Calibrate',Parameters:''});await refresh();});
$('halt').onclick=()=>run(async()=>{await alpaca('halt',{});await refresh();});
$('apply').onclick=()=>run(async()=>{await json(setup+'/settings',fc3?{speed:Number($('speed').value),reverse:$('reverse').checked,backlash:Number($('backlash').value)}:{beep:$('beep').checked,reverse:$('reverse').checked,backlash:Number($('backlash').value),max_step:Number($('limit').value)});initialized=false;await refresh();});
$('save-filters').onclick=()=>run(async()=>{if(connected){const status=JSON.parse(await alpaca('action',{Action:'Regain.Status',Parameters:''}));if(status.moving||status.fault||status.error)throw Error('Wait for the wheel to finish before saving filters');}const updated={...profile,names:Array.from(document.querySelectorAll('[data-filter-name]'),v=>v.value.trim()),focusOffsets:Array.from(document.querySelectorAll('[data-filter-offset]'),v=>Number(v.value)),unidirectional:$('unidirectional').checked};if(connected){await alpaca('connected',{Connected:false});connected=false;$('connect').textContent='Connect for setup';$('device').disabled=false;$('scan').disabled=false;$('connection').textContent='Disconnected';}await json(setup,updated);profile=updated;});
$('title').textContent=$('device-title').textContent=wheel?'EFW filter wheel':eta?'Wanderer Astro ETA M54':fc3?'Pegasus FocusCube3':'EAF focuser';$('target-label').textContent=wheel?'Filter slot (1–N)':'Absolute position (steps)';$('target').min=wheel?1:0;$(wheel?'efw':'eaf').hidden=false;if(fc3){$('beep').parentElement.hidden=true;$('limit').parentElement.hidden=true;$('backlash').max=1000;$('speed').parentElement.hidden=false;$('transport').textContent='Device 1 · Native USB serial';}$('halt').hidden=wheel||eta;
if(eta){$('eaf').hidden=true;$('eta').hidden=false;$('transport').textContent='Device 2 · Native serial · select by port';}
$('move-point').onclick=()=>run(async()=>{const point=Number($('point').value),position=Number($('point-target').value);if(!Number.isInteger(position)||position<0||position>1200)throw Error('Enter a whole position from 0 to 1200 µm');await alpaca('action',{Action:'Regain.MovePoint',Parameters:JSON.stringify({point,position})});await refresh();});
$('cancel-queued').onclick=()=>run(async()=>{await alpaca('action',{Action:'Regain.CancelQueued',Parameters:''});await refresh();});
setInterval(()=>{if(connected&&!busy)run(refresh);},750);
window.addEventListener('pagehide',()=>{if(connected)fetch(api+'connected',{method:'PUT',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({ClientID:client,Connected:false}),keepalive:true}).catch(()=>{});});
run(load);
