<Project>
  <PropertyGroup>
    <Version>0.4.0.0</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <Authors>Yann Ramin</Authors>
    <Company>PulsarFab</Company>
    <Copyright>Copyright 2026 Yann Ramin</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/pulsarfab/regain</RepositoryUrl>
    <ApplicationIcon>$(MSBuildThisFileDirectory)assets/regain.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
