<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
    <AssemblyTitle>ZWOgain</AssemblyTitle>
    <Title>ZWOgain</Title>
    <Description>ZWO camera, CAA, EFW and EAF drivers</Description>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets/zwogain.png" />
    <InternalsVisibleTo Include="ZwoGain.NINA.Tests" />
    <ProjectReference Include="../ZwoGain.Core/ZwoGain.Core.csproj" />
    <ProjectReference Include="../ZwoGain.Rotator/ZwoGain.Rotator.csproj" />
    <PackageReference Include="NINA.Plugin" Version="3.2.0.9001" PrivateAssets="all" />
  </ItemGroup>
</Project>
