<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>Regain.Hub.Client.Fixture</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../HubAccessoryServer.cs" Link="HubAccessoryServer.cs" />
    <Compile Include="../HubImageFixture.cs" Link="HubImageFixture.cs" />
    <Compile Include="../HubCameraHostFixture.cs" Link="HubCameraHostFixture.cs" />
    <Compile Include="../HubCameraOutputFixture.cs" Link="HubCameraOutputFixture.cs" />
    <Compile Include="../HubTimingFixture.cs" Link="HubTimingFixture.cs" />
    <ProjectReference Include="../../../src/Regain.Rotator/Regain.Rotator.csproj" />
    <ProjectReference Include="../../../src/Regain.Hub.ASCOM/Regain.Hub.ASCOM.csproj" />
  </ItemGroup>
</Project>
