//! Generate the standalone setup contract and compatible managed options.
use regain_core::recovery::{RecoveryOptions, RecoveryType};
use std::{error::Error, fmt::Write, path::Path};

fn managed_options() -> String {
    let mut text = String::from(
        "// Generated by regain-core export_recovery; edit recovery.rs instead.\nnamespace Regain.Core;\n\npublic sealed record RecoveryOptions\n{\n",
    );
    let fields = RecoveryOptions::fields();
    for field in &fields {
        let name = format!("{}{}", field.key[..1].to_uppercase(), &field.key[1..]);
        let ty = match field.value_type {
            RecoveryType::Integer(_, _) => "int",
            RecoveryType::Number { .. } => "double",
            RecoveryType::Boolean => "bool",
        };
        writeln!(
            text,
            "    public {ty} {name} {{ get; init; }} = {};",
            field.default
        )
        .unwrap();
    }
    text.push_str("    public void Validate()\n    {\n");
    for field in fields {
        let name = format!("{}{}", field.key[..1].to_uppercase(), &field.key[1..]);
        let condition = match field.value_type {
            RecoveryType::Integer(min, max) => format!("{name} < {min} || {name} > {max}"),
            RecoveryType::Number {
                minimum,
                exclusive,
                maximum,
            } => format!(
                "double.IsNaN({name}) || double.IsInfinity({name}) || {name} {} {minimum} || {name} > {maximum}",
                if exclusive { "<=" } else { "<" }
            ),
            RecoveryType::Boolean => continue,
        };
        writeln!(text, "        if ({condition})\n            throw new System.ArgumentOutOfRangeException(nameof({name}));").unwrap();
    }
    text.push_str("    }\n}\n");
    text
}

fn save(path: &Path, text: &str, check: bool) -> Result<(), Box<dyn Error>> {
    if check {
        if std::fs::read_to_string(path)?.replace("\r\n", "\n") != text {
            return Err(format!(
                "{} is stale; regenerate with export_recovery",
                path.display()
            )
            .into());
        }
    } else {
        std::fs::write(path, text)?;
    }
    Ok(())
}

fn main() -> Result<(), Box<dyn Error>> {
    let mut args = std::env::args().skip(1);
    let contract = args
        .next()
        .ok_or("Usage: export_recovery CONTRACT MANAGED [--check]")?;
    let managed = args
        .next()
        .ok_or("Usage: export_recovery CONTRACT MANAGED [--check]")?;
    let option = args.next();
    if option.as_deref().is_some_and(|s| s != "--check") || args.next().is_some() {
        return Err("Unknown option".into());
    }
    let description = serde_json::json!({"contractVersion":1,"schema":RecoveryOptions::schema()});
    save(
        Path::new(&contract),
        &(serde_json::to_string_pretty(&description)? + "\n"),
        option.is_some(),
    )?;
    save(Path::new(&managed), &managed_options(), option.is_some())
}
