<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Prefer32Bit>false</Prefer32Bit>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ZwoGain.ASCOM/ZwoGain.ASCOM.csproj" />
  </ItemGroup>
  <ItemGroup><ProjectReference Include="../ZwoGain.FocusCube.ASCOM/ZwoGain.FocusCube.ASCOM.csproj" ReferenceOutputAssembly="false" /></ItemGroup>
  <Target Name="CopyFocusCubeServer" AfterTargets="Build">
    <ItemGroup><FocusCubeFiles Include="../ZwoGain.FocusCube.ASCOM/bin/$(Configuration)/net48/ZwoGain.FocusCube.ASCOM.exe*" /></ItemGroup>
    <Copy SourceFiles="@(FocusCubeFiles)" DestinationFolder="$(OutDir)" />
  </Target>
</Project>
