'use strict';
const $ = id => document.getElementById(id);
let state, current = 0, choices = [];
const fields = [
  ['retry-fields','maxRetries','Replacement exposures',0,20,1],
  ['retry-fields','maximumRetryExposureSeconds','Maximum exposure to replace (s)',0,86400,1],
  ['retry-fields','readyFrameDownloadRetries','SDK read retries',0,5,1],
  ['retry-fields','directReadRetries','Direct read retries',0,5,1],
  ['retry-fields','reconnectDelaySeconds','Reconnect delay (s)',.001,3600,.1],
  ['timeout-fields','commandTimeoutSeconds','Command timeout (s)',.001,3600,1],
  ['timeout-fields','downloadTimeoutSeconds','Download timeout (s)',.001,3600,1],
  ['timeout-fields','exposureGraceSeconds','Exposure grace (s)',.001,3600,1],
  ['cooling-fields','coolingTimeoutSeconds','Cooling timeout (s)',.001,3600,1],
  ['cooling-fields','temperatureToleranceC','Temperature tolerance (°C)',.001,3600,.1],
  ['cooling-fields','coolingStableSamples','Stable samples',1,60,1],
  ['cooling-fields','coolingSampleSeconds','Sample interval (s)',.001,3600,.1]
];
const controls = [[0,'Gain'],[5,'Offset'],[6,'USB limit'],[21,'Dew heater (0–1)'],[22,'Fan speed'],[23,'Power LED brightness']];
for(const [parent,key,text,min,max,step] of fields){const label=document.createElement('label');label.textContent=text;const input=document.createElement('input');Object.assign(input,{type:'number',id:key,min,max,step:min===.001?'any':step,required:true});label.append(input);$(parent).append(label);}
for(const [id,text] of controls){const label=document.createElement('label');label.textContent=text;const input=document.createElement('input');Object.assign(input,{type:'number',id:'control-'+id,step:1,placeholder:'Keep camera setting'});label.append(input);$('control-fields').append(label);}
async function api(url,body){const response=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const text=await response.text();let value;try{value=text?JSON.parse(text):null;}catch{throw Error(text||response.statusText);}if(!response.ok)throw Error(value?.error||response.statusText);return value;}
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function title(camera){return camera?.name?.replace('ZWO ASI2600MM Duo','ASI2600MM Pro').replace('ZWO ASI220MM Mini','ASI220MM Mini (guide)')||'No camera selected';}
function renderSlots(){const nav=$('slots');nav.replaceChildren();for(const row of state.cameras){const button=document.createElement('button');button.type='button';const name=document.createElement('span');name.textContent=row.profile.label;const detail=document.createElement('small');detail.textContent=`Device ${row.slot} · ${row.connected?'Connected':title(row.profile.camera)}`;button.append(name,detail);button.classList.toggle('active',row.slot===current);button.onclick=()=>select(row.slot);nav.append(button);}}
function geometry(){const c=choices[$('camera-choice').value];$('geometry').textContent=c?`${c.width} × ${c.height} · ${c.color?'Bayer RAW16':'Mono RAW16'} · Binning ${c.bins.join(', ')} · ROI minimum ${c.minimumWidth??8} × ${c.minimumHeight??2}, origin alignment ${c.originAlignmentX??c.originAlignment??1} × ${c.originAlignmentY??(c.originAlignment?2:1)}`:'';}
function renderChoices(selected){const picker=$('camera-choice');picker.replaceChildren(new Option('No camera selected',''));choices.forEach((c,i)=>picker.add(new Option(title(c),String(i))));picker.value=selected>=0?String(selected):'';geometry();}
function select(slot){current=slot;const row=state.cameras.find(c=>c.slot===slot),p=row.profile;renderSlots();$('title').textContent=p.label;$('connection').textContent=`Device ${slot} · ${row.connected?'Connected — disconnect all clients to edit':'Disconnected'}`;$('save').disabled=row.connected;$('scan').disabled=state.cameras.some(c=>c.connected);$('label').value=p.label;$('serial').value=p.serial||'';$('backend').value=p.direct?'direct':'sdk';$('fallback').checked=p.sdkFallback;$('fallback').disabled=!p.direct;choices=p.camera?[p.camera]:[];renderChoices(p.camera?0:-1);for(const [,key] of fields)$(key).value=p.recovery[key];for(const [id] of controls)$('control-'+id).value=p.controls[id]??'';$('target').value=p.controls[16]??'';$('cooler-on').value=p.controls[17]??'';status('');}
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b===button));document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==button.dataset.tab);});
$('backend').onchange=()=>{$('fallback').disabled=$('backend').value!=='direct';if($('fallback').disabled)$('fallback').checked=false;};
$('camera-choice').onchange=()=>{const saved=state.cameras[current].profile;$('serial').value=choices[$('camera-choice').value]?.name===saved.camera?.name?(saved.serial||''):'';geometry();};
$('scan').onclick=async()=>{try{$('scan').disabled=true;status('Finding cameras…');const saved=choices[$('camera-choice').value];choices=await api('/setup/api/discover',{direct:$('backend').value==='direct'});renderChoices(choices.findIndex(c=>c.name===saved?.name));status(`Found ${choices.length} camera${choices.length===1?'':'s'}.`);}catch(e){status(e.message,true);}finally{$('scan').disabled=false;}};
$('save').onclick=async()=>{const invalid=$('settings').querySelector(':invalid');if(invalid){document.querySelector('[data-tab='+invalid.closest('.panel').id+']').click();invalid.reportValidity();return;}try{const profile=structuredClone(state.cameras[current].profile);profile.label=$('label').value.trim();profile.camera=choices[$('camera-choice').value]||null;profile.serial=$('serial').value.trim()||null;profile.direct=$('backend').value==='direct';profile.sdkFallback=profile.direct&&$('fallback').checked;for(const [,key] of fields)profile.recovery[key]=Number($(key).value);profile.controls={};for(const [id] of controls)if($('control-'+id).value!=='')profile.controls[id]=Number($('control-'+id).value);if($('target').value!=='')profile.controls[16]=Number($('target').value);if($('cooler-on').value!=='')profile.controls[17]=Number($('cooler-on').value);await api(`/setup/api/cameras/${current}`,profile);state=await api('/setup/api/state');select(current);status('Settings saved.');}catch(e){status(e.message,true);}};
$('add').onclick=async()=>{try{const added=await api('/setup/api/slots',{});state=await api('/setup/api/state');select(added.slot);}catch(e){status(e.message,true);}};
async function refresh(){try{const latest=await api('/setup/api/state');$('log').textContent=latest.logs.join('\n');for(const row of state.cameras){const next=latest.cameras.find(c=>c.slot===row.slot);if(next)row.connected=next.connected;}renderSlots();const connected=state.cameras[current].connected;$('save').disabled=connected;$('scan').disabled=state.cameras.some(c=>c.connected);$('connection').textContent=`Device ${current} · ${connected?'Connected — disconnect all clients to edit':'Disconnected'}`;}catch(e){status(`Server unavailable: ${e.message}`,true);}}
(async()=>{try{state=await api('/setup/api/state');$('version').textContent=state.version;$('simulation').hidden=!state.simulation;const route=location.pathname.match(/camera\/(\d+)\/setup/);select(route&&state.cameras.some(c=>c.slot===Number(route[1]))?Number(route[1]):0);$('log').textContent=state.logs.join('\n');setInterval(refresh,3000);}catch(e){status(e.message,true);}})();
