//! Shared hub policy. Frontends render configuration and translate interfaces;
//! they must not reimplement safety decisions or invent source capabilities.
pub mod activity;
pub mod alpaca;
pub mod ascom_export;
pub mod camera;
pub mod capabilities;
pub mod client;
pub mod com;
pub mod config;
pub mod coordination;
pub mod covercalibrator;
pub mod credentials;
pub mod description;
pub mod diagnostics;
pub mod discovery;
pub mod endpoint;
pub mod factory;
pub mod filterwheel;
pub mod focuser;
pub mod host;
pub mod ipc;
pub mod launch;
pub mod native;
pub mod native_reference;
mod output;
pub mod parameters;
pub mod readout;
pub mod rotator;
pub mod runtime;
pub mod safety;
pub mod safety_output;
pub mod sampling;
pub mod service;
pub mod simulated;
pub mod source;
pub mod switch;
mod typed_source;
mod virtual_source;
pub mod weather;
