//! Shared hub policy. Frontends render configuration and translate interfaces;
//! they must not reimplement safety decisions or invent source capabilities.
pub mod alpaca;
pub mod ascom_export;
pub mod capabilities;
pub mod client;
pub mod com;
pub mod config;
pub mod credentials;
pub mod description;
pub mod endpoint;
pub mod factory;
pub mod host;
pub mod ipc;
pub mod launch;
pub mod native;
mod output;
pub mod parameters;
pub mod readout;
pub mod runtime;
pub mod safety;
pub mod safety_output;
pub mod sampling;
pub mod service;
pub mod simulated;
pub mod source;
pub mod switch;
mod virtual_source;
pub mod weather;
