//! Shared hub policy. Frontends render configuration and translate interfaces;
//! they must not reimplement safety decisions or invent source capabilities.
pub mod alpaca;
pub mod config;
pub mod credentials;
pub mod description;
pub mod endpoint;
pub mod factory;
pub mod host;
pub mod ipc;
pub mod native;
pub mod parameters;
pub mod readout;
pub mod runtime;
pub mod safety;
pub mod safety_output;
pub mod service;
pub mod source;
pub mod switch;
pub mod weather;
