// Generated by regain-core export_recovery; edit recovery.rs instead.
namespace Regain.Core;

public sealed record RecoveryOptions
{
    public int MaxRetries { get; init; } = 3;
    public double MaximumRetryExposureSeconds { get; init; } = 30.0;
    public double ReconnectDelaySeconds { get; init; } = 5.0;
    public double CommandTimeoutSeconds { get; init; } = 15.0;
    public double DownloadTimeoutSeconds { get; init; } = 60.0;
    public double ExposureGraceSeconds { get; init; } = 30.0;
    public double CoolingTimeoutSeconds { get; init; } = 300.0;
    public double TemperatureToleranceC { get; init; } = 2.0;
    public int CoolingStableSamples { get; init; } = 3;
    public double CoolingSampleSeconds { get; init; } = 2.0;
    public int ReadyFrameDownloadRetries { get; init; } = 2;
    public int DirectReadRetries { get; init; } = 2;
    public int UsbResetAfterFailures { get; init; } = 0;
    public bool UsbPortCycle { get; init; } = false;
    public void Validate()
    {
        if (MaxRetries < 0 || MaxRetries > 20)
            throw new System.ArgumentOutOfRangeException(nameof(MaxRetries));
        if (double.IsNaN(MaximumRetryExposureSeconds) || double.IsInfinity(MaximumRetryExposureSeconds) || MaximumRetryExposureSeconds < 0 || MaximumRetryExposureSeconds > 86400)
            throw new System.ArgumentOutOfRangeException(nameof(MaximumRetryExposureSeconds));
        if (double.IsNaN(ReconnectDelaySeconds) || double.IsInfinity(ReconnectDelaySeconds) || ReconnectDelaySeconds <= 0 || ReconnectDelaySeconds > 3600)
            throw new System.ArgumentOutOfRangeException(nameof(ReconnectDelaySeconds));
        if (double.IsNaN(CommandTimeoutSeconds) || double.IsInfinity(CommandTimeoutSeconds) || CommandTimeoutSeconds <= 0 || CommandTimeoutSeconds > 3600)
            throw new System.ArgumentOutOfRangeException(nameof(CommandTimeoutSeconds));
        if (double.IsNaN(DownloadTimeoutSeconds) || double.IsInfinity(DownloadTimeoutSeconds) || DownloadTimeoutSeconds <= 0 || DownloadTimeoutSeconds > 3600)
            throw new System.ArgumentOutOfRangeException(nameof(DownloadTimeoutSeconds));
        if (double.IsNaN(ExposureGraceSeconds) || double.IsInfinity(ExposureGraceSeconds) || ExposureGraceSeconds <= 0 || ExposureGraceSeconds > 3600)
            throw new System.ArgumentOutOfRangeException(nameof(ExposureGraceSeconds));
        if (double.IsNaN(CoolingTimeoutSeconds) || double.IsInfinity(CoolingTimeoutSeconds) || CoolingTimeoutSeconds <= 0 || CoolingTimeoutSeconds > 3600)
            throw new System.ArgumentOutOfRangeException(nameof(CoolingTimeoutSeconds));
        if (double.IsNaN(TemperatureToleranceC) || double.IsInfinity(TemperatureToleranceC) || TemperatureToleranceC <= 0 || TemperatureToleranceC > 3600)
            throw new System.ArgumentOutOfRangeException(nameof(TemperatureToleranceC));
        if (CoolingStableSamples < 1 || CoolingStableSamples > 60)
            throw new System.ArgumentOutOfRangeException(nameof(CoolingStableSamples));
        if (double.IsNaN(CoolingSampleSeconds) || double.IsInfinity(CoolingSampleSeconds) || CoolingSampleSeconds <= 0 || CoolingSampleSeconds > 3600)
            throw new System.ArgumentOutOfRangeException(nameof(CoolingSampleSeconds));
        if (ReadyFrameDownloadRetries < 0 || ReadyFrameDownloadRetries > 5)
            throw new System.ArgumentOutOfRangeException(nameof(ReadyFrameDownloadRetries));
        if (DirectReadRetries < 0 || DirectReadRetries > 5)
            throw new System.ArgumentOutOfRangeException(nameof(DirectReadRetries));
        if (UsbResetAfterFailures < 0 || UsbResetAfterFailures > 20)
            throw new System.ArgumentOutOfRangeException(nameof(UsbResetAfterFailures));
    }
}
